apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: validation-policy
spec:
  validationFailureAction: Enforce
  rules:
  - name: validation-policy
    match:
      any:
      - resources:
          kinds:
          - Pod
    validate:
      message: "You must have set cpu and memory usage in all pods."
      pattern:
        spec:
            containers:
              - resources:
                  requests:
                    memory: "?*"
                    cpu: "?*"
                  limits:
                    memory: "?*"
